### ISSUE TITLE
외부함수 호출하는 방법

### ISSUE THREAD

**Issue by woonooo** [Keunyoung-Jung/go-study-mysterico#3]
```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("점수를 입력하세요")
	var score int
	fmt.Scanln(&score)

	Return_grade(score)
}
```
이것이 main.go의 내용이고    
아래의 것이 Return_grade함수가 있는 코드는 아래의 것입니다.   
```go
package Grade_switch

import "fmt"

func Return_grade(score int) {
	var grade string
	switch {
	case score > 90:
		grade = "A"
	case score > 70:
		grade = "B"
	case score > 50:
		grade = "C"
	default:
		grade = "F"
	}

	fmt.Println("성적은", grade, "입니다")
}
```
실행 시켜주실분 누구일까요??ㅎㅎㅎㅎ

**Comment by octavesop** [comment]
## 성공했습니당!🎊

**디렉토리 구성(Windows)**
```
C:\USERS\***\DOCUMENTS\GITHUB\GO-TEST
│  go.mod
│
├─bin
├─pkg
└─src
    │  main.go
    │
    └─lib
            returnGrade.go
```

**main.go**
```
package main

import (
	"go-test/src/lib"
)

func main() {
	lib.Return_grade(30)
}
```

**go.mod**
```
module go-test

go 1.17
```

**returnGrade.go**
`기존과 동일`


---
## 방법

- `go mod init (이름)` 명령어로 go.mod 파일을 생성합니다.
-  import를 할 때 상대경로가 아닌 go.mod가 있는 디렉토리를 기준으로 경로를 작성해줍니다.
- `go run main.go` 로 실행합니다!
- 왜 이렇게 동작하는지는 package와 관련하여 다음주에 밝혀질 것 같습니당!🥰

**Comment by keyog0** [comment]
정아님이 원하는 동작하는게 확인 됬으면 Issue는 정아님이 close 해주세요

**Comment by keyog0** [comment]
민아님은 Issue branch 통해서 해당 내용 폴더구조 생성해서 테스트하신 후에 main으로 merge 부탁드립니다.
merge 후에는 해당 브랜치 삭제해주세요~
branch는 제가 만들어 둘테니 해당 branch 이용해서 작성해주세요
